//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWA {
	
	
	public partial class Briefing {
		
		protected System.Web.UI.WebControls.ContentPlaceHolder head;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected PWA.Controls.Header Header;
		
		protected PWA.Controls.Banner Banner;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder ContentPlaceHolder1;
		
		protected PWA.Controls.Footer Footer;
	}
}
