//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTask
    {
        public int Id { get; set; }
        public System.DateTime DateSet { get; set; }
        public string Category { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public int Complete { get; set; }
        public int userId { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
