//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWA.Controls {
    
    
    public partial class Banner {
        
        protected System.Web.UI.WebControls.Label lblBan;
        
        protected System.Web.UI.WebControls.Label lblTime;
        
        protected PWA.Controls.Clock clock;
        
        protected System.Web.UI.WebControls.Label lblLocation;
        
        protected PWA.Controls.Navigation Navigation;
    }
}
