//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWA.Pages {
	
	
	public partial class Profile {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.WebControls.TextBox txtFname;
		
		protected System.Web.UI.WebControls.TextBox txtLName;
		
		protected System.Web.UI.WebControls.TextBox txtAdd1;
		
		protected System.Web.UI.WebControls.TextBox txtCity;
		
		protected System.Web.UI.WebControls.TextBox txtState;
		
		protected System.Web.UI.WebControls.TextBox txtCountry;
		
		protected System.Web.UI.WebControls.Button SendCookie;
	}
}
