//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWA.Pages {
	
	
	public partial class Weather {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.WebControls.TextBox txtCity;
		
		protected System.Web.UI.HtmlControls.HtmlTable tblWeather;
		
		protected System.Web.UI.WebControls.Image imgWeatherIcon;
		
		protected System.Web.UI.WebControls.Label lblCity_Country;
		
		protected System.Web.UI.WebControls.Image imgCountryFlag;
		
		protected System.Web.UI.WebControls.Label lblDescription;
		
		protected System.Web.UI.WebControls.Label lblHumidity;
		
		protected System.Web.UI.WebControls.Label lblTempMin;
		
		protected System.Web.UI.WebControls.Label lblTempMax;
		
		protected System.Web.UI.WebControls.Label lblTempDay;
		
		protected System.Web.UI.WebControls.Label lblTempNight;
	}
}
